const questions = [
  // ===== Arrays & Hashing =====
  {
    id: 1,
    title: "Two Sum",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    link: "https://leetcode.com/problems/two-sum/",
    gfg: "https://www.geeksforgeeks.org/check-if-pair-with-given-sum-exists-in-array/",
  },
  {
    id: 2,
    title: "Contains Duplicate",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    link: "https://leetcode.com/problems/contains-duplicate/",
    gfg: "https://www.geeksforgeeks.org/find-duplicates-in-on-time-and-constant-extra-space/",
  },
  {
    id: 3,
    title: "Valid Anagram",
    difficulty: "Easy",
    pattern: "Arrays & Hashing",
    link: "https://leetcode.com/problems/valid-anagram/",
    gfg: "https://www.geeksforgeeks.org/check-whether-two-strings-are-anagram-of-each-other/",
  },
  {
    id: 4,
    title: "Group Anagrams",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    link: "https://leetcode.com/problems/group-anagrams/",
    gfg: "https://www.geeksforgeeks.org/given-a-sequence-of-words-print-all-anagrams-together/",
  },
  {
    id: 5,
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    link: "https://leetcode.com/problems/top-k-frequent-elements/",
    gfg: "https://www.geeksforgeeks.org/find-k-numbers-occurrences-given-array/",
  },
  {
    id: 6,
    title: "Product of Array Except Self",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    link: "https://leetcode.com/problems/product-of-array-except-self/",
    gfg: "https://www.geeksforgeeks.org/a-product-array-puzzle/",
  },
  {
    id: 7,
    title: "Longest Consecutive Sequence",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    link: "https://leetcode.com/problems/longest-consecutive-sequence/",
    gfg: "https://www.geeksforgeeks.org/longest-consecutive-subsequence/",
  },
  {
    id: 8,
    title: "Encode and Decode Strings",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    link: "https://leetcode.com/problems/encode-and-decode-strings/",
  },
  {
    id: 9,
    title: "Subarray Sum Equals K",
    difficulty: "Medium",
    pattern: "Arrays & Hashing",
    link: "https://leetcode.com/problems/subarray-sum-equals-k/",
    gfg: "https://www.geeksforgeeks.org/find-subarray-with-given-sum/",
  },
  {
    id: 10,
    title: "First Missing Positive",
    difficulty: "Hard",
    pattern: "Arrays & Hashing",
    link: "https://leetcode.com/problems/first-missing-positive/",
    gfg: "https://www.geeksforgeeks.org/find-the-smallest-positive-number-missing-from-an-unsorted-array/",
  },

  // ===== Two Pointers =====
  {
    id: 11,
    title: "Valid Palindrome",
    difficulty: "Easy",
    pattern: "Two Pointers",
    link: "https://leetcode.com/problems/valid-palindrome/",
    gfg: "https://www.geeksforgeeks.org/check-if-a-string-is-palindrome/",
  },
  {
    id: 12,
    title: "Two Sum II - Input Array Is Sorted",
    difficulty: "Medium",
    pattern: "Two Pointers",
    link: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
    gfg: "https://www.geeksforgeeks.org/given-sorted-array-number-x-find-pair-array-whose-sum-closest-x/",
  },
  {
    id: 13,
    title: "3Sum",
    difficulty: "Medium",
    pattern: "Two Pointers",
    link: "https://leetcode.com/problems/3sum/",
    gfg: "https://www.geeksforgeeks.org/find-triplets-array-whose-sum-equal-zero/",
  },
  {
    id: 14,
    title: "Container With Most Water",
    difficulty: "Medium",
    pattern: "Two Pointers",
    link: "https://leetcode.com/problems/container-with-most-water/",
    gfg: "https://www.geeksforgeeks.org/container-with-most-water/",
  },
  {
    id: 15,
    title: "Remove Duplicates from Sorted Array",
    difficulty: "Easy",
    pattern: "Two Pointers",
    link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
    gfg: "https://www.geeksforgeeks.org/remove-duplicates-sorted-array/",
  },
  {
    id: 16,
    title: "Move Zeroes",
    difficulty: "Easy",
    pattern: "Two Pointers",
    link: "https://leetcode.com/problems/move-zeroes/",
    gfg: "https://www.geeksforgeeks.org/move-zeroes-end-array/",
  },
  {
    id: 17,
    title: "Sort Colors",
    difficulty: "Medium",
    pattern: "Two Pointers",
    link: "https://leetcode.com/problems/sort-colors/",
    gfg: "https://www.geeksforgeeks.org/sort-an-array-of-0s-1s-and-2s/",
  },
  {
    id: 18,
    title: "4Sum",
    difficulty: "Medium",
    pattern: "Two Pointers",
    link: "https://leetcode.com/problems/4sum/",
    gfg: "https://www.geeksforgeeks.org/find-four-elements-that-sum-to-a-given-value/",
  },
  {
    id: 19,
    title: "Trapping Rain Water",
    difficulty: "Hard",
    pattern: "Two Pointers",
    link: "https://leetcode.com/problems/trapping-rain-water/",
    gfg: "https://www.geeksforgeeks.org/trapping-rain-water/",
  },

  // ===== Sliding Window =====
  {
    id: 20,
    title: "Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    pattern: "Sliding Window",
    link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    gfg: "https://www.geeksforgeeks.org/best-time-to-buy-and-sell-stock/",
  },
  {
    id: 21,
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    pattern: "Sliding Window",
    link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    gfg: "https://www.geeksforgeeks.org/length-of-the-longest-substring-without-repeating-characters/",
  },
  {
    id: 22,
    title: "Longest Repeating Character Replacement",
    difficulty: "Medium",
    pattern: "Sliding Window",
    link: "https://leetcode.com/problems/longest-repeating-character-replacement/",
  },
  {
    id: 23,
    title: "Permutation in String",
    difficulty: "Medium",
    pattern: "Sliding Window",
    link: "https://leetcode.com/problems/permutation-in-string/",
    gfg: "https://www.geeksforgeeks.org/check-if-any-anagram-of-a-string-is-palindrome-or-not/",
  },
  {
    id: 24,
    title: "Minimum Window Substring",
    difficulty: "Hard",
    pattern: "Sliding Window",
    link: "https://leetcode.com/problems/minimum-window-substring/",
    gfg: "https://www.geeksforgeeks.org/find-the-smallest-window-in-a-string-containing-all-characters-of-another-string/",
  },
  {
    id: 25,
    title: "Sliding Window Maximum",
    difficulty: "Hard",
    pattern: "Sliding Window",
    link: "https://leetcode.com/problems/sliding-window-maximum/",
    gfg: "https://www.geeksforgeeks.org/sliding-window-maximum-maximum-of-all-subarrays-of-size-k/",
  },
  {
    id: 26,
    title: "Maximum Average Subarray I",
    difficulty: "Easy",
    pattern: "Sliding Window",
    link: "https://leetcode.com/problems/maximum-average-subarray-i/",
  },
  {
    id: 27,
    title: "Minimum Size Subarray Sum",
    difficulty: "Medium",
    pattern: "Sliding Window",
    link: "https://leetcode.com/problems/minimum-size-subarray-sum/",
    gfg: "https://www.geeksforgeeks.org/minimum-length-subarray-sum-greater-given-value/",
  },
  {
    id: 28,
    title: "Fruit Into Baskets",
    difficulty: "Medium",
    pattern: "Sliding Window",
    link: "https://leetcode.com/problems/fruit-into-baskets/",
  },
  {
    id: 29,
    title: "Substring with Concatenation of All Words",
    difficulty: "Hard",
    pattern: "Sliding Window",
    link: "https://leetcode.com/problems/substring-with-concatenation-of-all-words/",
  },

  // ===== Stack =====
  {
    id: 30,
    title: "Valid Parentheses",
    difficulty: "Easy",
    pattern: "Stack",
    link: "https://leetcode.com/problems/valid-parentheses/",
    gfg: "https://www.geeksforgeeks.org/check-for-balanced-parentheses-in-an-expression/",
  },
  {
    id: 31,
    title: "Min Stack",
    difficulty: "Medium",
    pattern: "Stack",
    link: "https://leetcode.com/problems/min-stack/",
    gfg: "https://www.geeksforgeeks.org/design-a-stack-that-supports-getmin-in-o1-time-and-o1-extra-space/",
  },
  {
    id: 32,
    title: "Evaluate Reverse Polish Notation",
    difficulty: "Medium",
    pattern: "Stack",
    link: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
    gfg: "https://www.geeksforgeeks.org/stack-set-4-evaluation-postfix-expression/",
  },
  {
    id: 33,
    title: "Daily Temperatures",
    difficulty: "Medium",
    pattern: "Stack",
    link: "https://leetcode.com/problems/daily-temperatures/",
    gfg: "https://www.geeksforgeeks.org/number-of-days-until-warmer-temperature/",
  },
  {
    id: 34,
    title: "Next Greater Element I",
    difficulty: "Easy",
    pattern: "Stack",
    link: "https://leetcode.com/problems/next-greater-element-i/",
    gfg: "https://www.geeksforgeeks.org/next-greater-element/",
  },
  {
    id: 35,
    title: "Largest Rectangle in Histogram",
    difficulty: "Hard",
    pattern: "Stack",
    link: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    gfg: "https://www.geeksforgeeks.org/largest-rectangle-under-histogram/",
  },
  {
    id: 36,
    title: "Car Fleet",
    difficulty: "Medium",
    pattern: "Stack",
    link: "https://leetcode.com/problems/car-fleet/",
  },
  {
    id: 37,
    title: "Decode String",
    difficulty: "Medium",
    pattern: "Stack",
    link: "https://leetcode.com/problems/decode-string/",
    gfg: "https://www.geeksforgeeks.org/decode-string-recursively-encoded-count-followed-substring/",
  },
  {
    id: 38,
    title: "Asteroid Collision",
    difficulty: "Medium",
    pattern: "Stack",
    link: "https://leetcode.com/problems/asteroid-collision/",
  },
  {
    id: 39,
    title: "Online Stock Span",
    difficulty: "Medium",
    pattern: "Stack",
    link: "https://leetcode.com/problems/online-stock-span/",
    gfg: "https://www.geeksforgeeks.org/the-stock-span-problem/",
  },

  // ===== Binary Search =====
  {
    id: 40,
    title: "Binary Search",
    difficulty: "Easy",
    pattern: "Binary Search",
    link: "https://leetcode.com/problems/binary-search/",
    gfg: "https://www.geeksforgeeks.org/binary-search/",
  },
  {
    id: 41,
    title: "Search a 2D Matrix",
    difficulty: "Medium",
    pattern: "Binary Search",
    link: "https://leetcode.com/problems/search-a-2d-matrix/",
    gfg: "https://www.geeksforgeeks.org/search-in-row-wise-and-column-wise-sorted-matrix/",
  },
  {
    id: 42,
    title: "Koko Eating Bananas",
    difficulty: "Medium",
    pattern: "Binary Search",
    link: "https://leetcode.com/problems/koko-eating-bananas/",
  },
  {
    id: 43,
    title: "Find Minimum in Rotated Sorted Array",
    difficulty: "Medium",
    pattern: "Binary Search",
    link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    gfg: "https://www.geeksforgeeks.org/find-minimum-element-in-a-sorted-and-rotated-array/",
  },
  {
    id: 44,
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium",
    pattern: "Binary Search",
    link: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    gfg: "https://www.geeksforgeeks.org/search-an-element-in-a-sorted-and-pivoted-array/",
  },
  {
    id: 45,
    title: "Find Peak Element",
    difficulty: "Medium",
    pattern: "Binary Search",
    link: "https://leetcode.com/problems/find-peak-element/",
    gfg: "https://www.geeksforgeeks.org/find-a-peak-in-a-given-array/",
  },
  {
    id: 46,
    title: "Search Insert Position",
    difficulty: "Easy",
    pattern: "Binary Search",
    link: "https://leetcode.com/problems/search-insert-position/",
  },
  {
    id: 47,
    title: "Find First and Last Position",
    difficulty: "Medium",
    pattern: "Binary Search",
    link: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
    gfg: "https://www.geeksforgeeks.org/find-first-and-last-positions-of-an-element-in-a-sorted-array/",
  },
  {
    id: 48,
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    pattern: "Binary Search",
    link: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    gfg: "https://www.geeksforgeeks.org/median-of-two-sorted-arrays/",
  },
  {
    id: 49,
    title: "Capacity To Ship Packages Within D Days",
    difficulty: "Medium",
    pattern: "Binary Search",
    link: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/",
  },

  // ===== Linked List =====
  {
    id: 50,
    title: "Reverse Linked List",
    difficulty: "Easy",
    pattern: "Linked List",
    link: "https://leetcode.com/problems/reverse-linked-list/",
    gfg: "https://www.geeksforgeeks.org/reverse-a-linked-list/",
  },
  {
    id: 51,
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    pattern: "Linked List",
    link: "https://leetcode.com/problems/merge-two-sorted-lists/",
    gfg: "https://www.geeksforgeeks.org/merge-two-sorted-linked-lists/",
  },
  {
    id: 52,
    title: "Linked List Cycle",
    difficulty: "Easy",
    pattern: "Linked List",
    link: "https://leetcode.com/problems/linked-list-cycle/",
    gfg: "https://www.geeksforgeeks.org/detect-loop-in-a-linked-list/",
  },
  {
    id: 53,
    title: "Reorder List",
    difficulty: "Medium",
    pattern: "Linked List",
    link: "https://leetcode.com/problems/reorder-list/",
  },
  {
    id: 54,
    title: "Remove Nth Node From End of List",
    difficulty: "Medium",
    pattern: "Linked List",
    link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    gfg: "https://www.geeksforgeeks.org/delete-nth-node-from-the-end-of-the-given-linked-list/",
  },
  {
    id: 55,
    title: "Add Two Numbers",
    difficulty: "Medium",
    pattern: "Linked List",
    link: "https://leetcode.com/problems/add-two-numbers/",
    gfg: "https://www.geeksforgeeks.org/add-two-numbers-represented-by-linked-lists/",
  },
  {
    id: 56,
    title: "Copy List with Random Pointer",
    difficulty: "Medium",
    pattern: "Linked List",
    link: "https://leetcode.com/problems/copy-list-with-random-pointer/",
    gfg: "https://www.geeksforgeeks.org/a-linked-list-with-next-and-arbit-pointer/",
  },
  {
    id: 57,
    title: "LRU Cache",
    difficulty: "Medium",
    pattern: "Linked List",
    link: "https://leetcode.com/problems/lru-cache/",
    gfg: "https://www.geeksforgeeks.org/lru-cache-implementation/",
  },
  {
    id: 58,
    title: "Merge K Sorted Lists",
    difficulty: "Hard",
    pattern: "Linked List",
    link: "https://leetcode.com/problems/merge-k-sorted-lists/",
    gfg: "https://www.geeksforgeeks.org/merge-k-sorted-linked-lists/",
  },
  {
    id: 59,
    title: "Reverse Nodes in k-Group",
    difficulty: "Hard",
    pattern: "Linked List",
    link: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
    gfg: "https://www.geeksforgeeks.org/reverse-a-linked-list-in-groups-of-given-size/",
  },

  // ===== Trees =====
  {
    id: 60,
    title: "Invert Binary Tree",
    difficulty: "Easy",
    pattern: "Trees",
    link: "https://leetcode.com/problems/invert-binary-tree/",
    gfg: "https://www.geeksforgeeks.org/write-an-efficient-c-function-to-convert-a-tree-into-its-mirror-tree/",
  },
  {
    id: 61,
    title: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    pattern: "Trees",
    link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    gfg: "https://www.geeksforgeeks.org/write-a-c-program-to-find-the-maximum-depth-or-height-of-a-tree/",
  },
  {
    id: 62,
    title: "Same Tree",
    difficulty: "Easy",
    pattern: "Trees",
    link: "https://leetcode.com/problems/same-tree/",
    gfg: "https://www.geeksforgeeks.org/write-c-code-to-determine-if-two-trees-are-identical/",
  },
  {
    id: 63,
    title: "Subtree of Another Tree",
    difficulty: "Easy",
    pattern: "Trees",
    link: "https://leetcode.com/problems/subtree-of-another-tree/",
  },
  {
    id: 64,
    title: "Lowest Common Ancestor of BST",
    difficulty: "Medium",
    pattern: "Trees",
    link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    gfg: "https://www.geeksforgeeks.org/lowest-common-ancestor-in-a-binary-search-tree/",
  },
  {
    id: 65,
    title: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    pattern: "Trees",
    link: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    gfg: "https://www.geeksforgeeks.org/level-order-tree-traversal/",
  },
  {
    id: 66,
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    pattern: "Trees",
    link: "https://leetcode.com/problems/validate-binary-search-tree/",
    gfg: "https://www.geeksforgeeks.org/a-program-to-check-if-a-binary-tree-is-bst-or-not/",
  },
  {
    id: 67,
    title: "Kth Smallest Element in a BST",
    difficulty: "Medium",
    pattern: "Trees",
    link: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
    gfg: "https://www.geeksforgeeks.org/find-k-th-smallest-element-in-bst-order-statistics-in-bst/",
  },
  {
    id: 68,
    title: "Construct Binary Tree from Preorder and Inorder",
    difficulty: "Medium",
    pattern: "Trees",
    link: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
    gfg: "https://www.geeksforgeeks.org/construct-tree-from-given-inorder-and-preorder-traversal/",
  },
  {
    id: 69,
    title: "Binary Tree Right Side View",
    difficulty: "Medium",
    pattern: "Trees",
    link: "https://leetcode.com/problems/binary-tree-right-side-view/",
  },
  {
    id: 70,
    title: "Diameter of Binary Tree",
    difficulty: "Easy",
    pattern: "Trees",
    link: "https://leetcode.com/problems/diameter-of-binary-tree/",
    gfg: "https://www.geeksforgeeks.org/diameter-of-a-binary-tree/",
  },
  {
    id: 71,
    title: "Balanced Binary Tree",
    difficulty: "Easy",
    pattern: "Trees",
    link: "https://leetcode.com/problems/balanced-binary-tree/",
    gfg: "https://www.geeksforgeeks.org/how-to-determine-if-a-binary-tree-is-balanced/",
  },
  {
    id: 72,
    title: "Binary Tree Maximum Path Sum",
    difficulty: "Hard",
    pattern: "Trees",
    link: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    gfg: "https://www.geeksforgeeks.org/find-maximum-path-sum-in-a-binary-tree/",
  },
  {
    id: 73,
    title: "Serialize and Deserialize Binary Tree",
    difficulty: "Hard",
    pattern: "Trees",
    link: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    gfg: "https://www.geeksforgeeks.org/serialize-deserialize-binary-tree/",
  },

  // ===== Tries =====
  {
    id: 74,
    title: "Implement Trie (Prefix Tree)",
    difficulty: "Medium",
    pattern: "Tries",
    link: "https://leetcode.com/problems/implement-trie-prefix-tree/",
    gfg: "https://www.geeksforgeeks.org/trie-insert-and-search/",
  },
  {
    id: 75,
    title: "Design Add and Search Words Data Structure",
    difficulty: "Medium",
    pattern: "Tries",
    link: "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
  },
  {
    id: 76,
    title: "Word Search II",
    difficulty: "Hard",
    pattern: "Tries",
    link: "https://leetcode.com/problems/word-search-ii/",
  },
  {
    id: 77,
    title: "Replace Words",
    difficulty: "Medium",
    pattern: "Tries",
    link: "https://leetcode.com/problems/replace-words/",
  },
  {
    id: 78,
    title: "Longest Word in Dictionary",
    difficulty: "Medium",
    pattern: "Tries",
    link: "https://leetcode.com/problems/longest-word-in-dictionary/",
  },

  // ===== Heap / Priority Queue =====
  {
    id: 79,
    title: "Kth Largest Element in a Stream",
    difficulty: "Easy",
    pattern: "Heap / Priority Queue",
    link: "https://leetcode.com/problems/kth-largest-element-in-a-stream/",
    gfg: "https://www.geeksforgeeks.org/kth-largest-element-in-a-stream/",
  },
  {
    id: 80,
    title: "Last Stone Weight",
    difficulty: "Easy",
    pattern: "Heap / Priority Queue",
    link: "https://leetcode.com/problems/last-stone-weight/",
  },
  {
    id: 81,
    title: "K Closest Points to Origin",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    link: "https://leetcode.com/problems/k-closest-points-to-origin/",
    gfg: "https://www.geeksforgeeks.org/find-k-closest-points-to-the-origin/",
  },
  {
    id: 82,
    title: "Task Scheduler",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    link: "https://leetcode.com/problems/task-scheduler/",
  },
  {
    id: 83,
    title: "Reorganize String",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    link: "https://leetcode.com/problems/reorganize-string/",
    gfg: "https://www.geeksforgeeks.org/rearrange-characters-string-no-two-adjacent/",
  },
  {
    id: 84,
    title: "Find Median from Data Stream",
    difficulty: "Hard",
    pattern: "Heap / Priority Queue",
    link: "https://leetcode.com/problems/find-median-from-data-stream/",
    gfg: "https://www.geeksforgeeks.org/median-of-stream-of-integers-running-integers/",
  },
  {
    id: 85,
    title: "Kth Largest Element in an Array",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    link: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    gfg: "https://www.geeksforgeeks.org/kth-smallestlargest-element-unsorted-array/",
  },
  {
    id: 86,
    title: "Top K Frequent Words",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    link: "https://leetcode.com/problems/top-k-frequent-words/",
  },
  {
    id: 87,
    title: "Sort Characters By Frequency",
    difficulty: "Medium",
    pattern: "Heap / Priority Queue",
    link: "https://leetcode.com/problems/sort-characters-by-frequency/",
  },

  // ===== Backtracking =====
  {
    id: 88,
    title: "Subsets",
    difficulty: "Medium",
    pattern: "Backtracking",
    link: "https://leetcode.com/problems/subsets/",
    gfg: "https://www.geeksforgeeks.org/power-set/",
  },
  {
    id: 89,
    title: "Combination Sum",
    difficulty: "Medium",
    pattern: "Backtracking",
    link: "https://leetcode.com/problems/combination-sum/",
    gfg: "https://www.geeksforgeeks.org/combinational-sum/",
  },
  {
    id: 90,
    title: "Permutations",
    difficulty: "Medium",
    pattern: "Backtracking",
    link: "https://leetcode.com/problems/permutations/",
    gfg: "https://www.geeksforgeeks.org/write-a-c-program-to-print-all-permutations-of-a-given-string/",
  },
  {
    id: 91,
    title: "Word Search",
    difficulty: "Medium",
    pattern: "Backtracking",
    link: "https://leetcode.com/problems/word-search/",
    gfg: "https://www.geeksforgeeks.org/search-a-word-in-a-2d-grid-of-characters/",
  },
  {
    id: 92,
    title: "Palindrome Partitioning",
    difficulty: "Medium",
    pattern: "Backtracking",
    link: "https://leetcode.com/problems/palindrome-partitioning/",
    gfg: "https://www.geeksforgeeks.org/given-a-string-print-all-possible-palindromic-partition/",
  },
  {
    id: 93,
    title: "Letter Combinations of a Phone Number",
    difficulty: "Medium",
    pattern: "Backtracking",
    link: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
    gfg: "https://www.geeksforgeeks.org/iterative-letter-combinations-of-a-phone-number/",
  },
  {
    id: 94,
    title: "N-Queens",
    difficulty: "Hard",
    pattern: "Backtracking",
    link: "https://leetcode.com/problems/n-queens/",
    gfg: "https://www.geeksforgeeks.org/n-queen-problem-backtracking-3/",
  },
  {
    id: 95,
    title: "Subsets II",
    difficulty: "Medium",
    pattern: "Backtracking",
    link: "https://leetcode.com/problems/subsets-ii/",
  },
  {
    id: 96,
    title: "Combination Sum II",
    difficulty: "Medium",
    pattern: "Backtracking",
    link: "https://leetcode.com/problems/combination-sum-ii/",
  },
  {
    id: 97,
    title: "Generate Parentheses",
    difficulty: "Medium",
    pattern: "Backtracking",
    link: "https://leetcode.com/problems/generate-parentheses/",
    gfg: "https://www.geeksforgeeks.org/print-all-combinations-of-balanced-parentheses/",
  },

  // ===== Graphs (BFS/DFS) =====
  {
    id: 98,
    title: "Number of Islands",
    difficulty: "Medium",
    pattern: "Graphs",
    link: "https://leetcode.com/problems/number-of-islands/",
    gfg: "https://www.geeksforgeeks.org/find-number-of-islands/",
  },
  {
    id: 99,
    title: "Clone Graph",
    difficulty: "Medium",
    pattern: "Graphs",
    link: "https://leetcode.com/problems/clone-graph/",
    gfg: "https://www.geeksforgeeks.org/clone-an-undirected-graph/",
  },
  {
    id: 100,
    title: "Pacific Atlantic Water Flow",
    difficulty: "Medium",
    pattern: "Graphs",
    link: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
  },
  {
    id: 101,
    title: "Course Schedule",
    difficulty: "Medium",
    pattern: "Graphs",
    link: "https://leetcode.com/problems/course-schedule/",
    gfg: "https://www.geeksforgeeks.org/detect-cycle-in-a-graph/",
  },
  {
    id: 102,
    title: "Course Schedule II",
    difficulty: "Medium",
    pattern: "Graphs",
    link: "https://leetcode.com/problems/course-schedule-ii/",
    gfg: "https://www.geeksforgeeks.org/topological-sorting/",
  },
  {
    id: 103,
    title: "Graph Valid Tree",
    difficulty: "Medium",
    pattern: "Graphs",
    link: "https://leetcode.com/problems/graph-valid-tree/",
  },
  {
    id: 104,
    title: "Rotting Oranges",
    difficulty: "Medium",
    pattern: "Graphs",
    link: "https://leetcode.com/problems/rotting-oranges/",
    gfg: "https://www.geeksforgeeks.org/minimum-time-required-so-that-all-oranges-become-rotten/",
  },
  {
    id: 105,
    title: "Walls and Gates",
    difficulty: "Medium",
    pattern: "Graphs",
    link: "https://leetcode.com/problems/walls-and-gates/",
  },
  {
    id: 106,
    title: "Surrounded Regions",
    difficulty: "Medium",
    pattern: "Graphs",
    link: "https://leetcode.com/problems/surrounded-regions/",
    gfg: "https://www.geeksforgeeks.org/given-matrix-o-x-replace-o-x-surrounded-x/",
  },
  {
    id: 107,
    title: "Word Ladder",
    difficulty: "Hard",
    pattern: "Graphs",
    link: "https://leetcode.com/problems/word-ladder/",
    gfg: "https://www.geeksforgeeks.org/word-ladder-length-of-shortest-chain-to-reach-a-target-word/",
  },
  {
    id: 108,
    title: "Shortest Path in Binary Matrix",
    difficulty: "Medium",
    pattern: "Graphs",
    link: "https://leetcode.com/problems/shortest-path-in-binary-matrix/",
  },
  {
    id: 109,
    title: "Open the Lock",
    difficulty: "Medium",
    pattern: "Graphs",
    link: "https://leetcode.com/problems/open-the-lock/",
  },

  // ===== Topological Sort =====
  {
    id: 110,
    title: "Alien Dictionary",
    difficulty: "Hard",
    pattern: "Topological Sort",
    link: "https://leetcode.com/problems/alien-dictionary/",
    gfg: "https://www.geeksforgeeks.org/given-sorted-dictionary-find-precedence-characters/",
  },
  {
    id: 111,
    title: "Task Scheduler II",
    difficulty: "Medium",
    pattern: "Topological Sort",
    link: "https://leetcode.com/problems/task-scheduler-ii/",
  },
  {
    id: 112,
    title: "Minimum Height Trees",
    difficulty: "Medium",
    pattern: "Topological Sort",
    link: "https://leetcode.com/problems/minimum-height-trees/",
  },
  {
    id: 113,
    title: "Longest Increasing Path in a Matrix",
    difficulty: "Hard",
    pattern: "Topological Sort",
    link: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/",
    gfg: "https://www.geeksforgeeks.org/longest-increasing-path-matrix/",
  },
  {
    id: 114,
    title: "Sequence Reconstruction",
    difficulty: "Medium",
    pattern: "Topological Sort",
    link: "https://leetcode.com/problems/sequence-reconstruction/",
  },

  // ===== 1D Dynamic Programming =====
  {
    id: 115,
    title: "Climbing Stairs",
    difficulty: "Easy",
    pattern: "1D Dynamic Programming",
    link: "https://leetcode.com/problems/climbing-stairs/",
    gfg: "https://www.geeksforgeeks.org/count-ways-reach-nth-stair/",
  },
  {
    id: 116,
    title: "House Robber",
    difficulty: "Medium",
    pattern: "1D Dynamic Programming",
    link: "https://leetcode.com/problems/house-robber/",
    gfg: "https://www.geeksforgeeks.org/find-maximum-possible-stolen-value-houses/",
  },
  {
    id: 117,
    title: "House Robber II",
    difficulty: "Medium",
    pattern: "1D Dynamic Programming",
    link: "https://leetcode.com/problems/house-robber-ii/",
  },
  {
    id: 118,
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    pattern: "1D Dynamic Programming",
    link: "https://leetcode.com/problems/longest-palindromic-substring/",
    gfg: "https://www.geeksforgeeks.org/longest-palindrome-substring-set-1/",
  },
  {
    id: 119,
    title: "Palindromic Substrings",
    difficulty: "Medium",
    pattern: "1D Dynamic Programming",
    link: "https://leetcode.com/problems/palindromic-substrings/",
  },
  {
    id: 120,
    title: "Decode Ways",
    difficulty: "Medium",
    pattern: "1D Dynamic Programming",
    link: "https://leetcode.com/problems/decode-ways/",
    gfg: "https://www.geeksforgeeks.org/count-possible-decodings-given-digit-sequence/",
  },
  {
    id: 121,
    title: "Coin Change",
    difficulty: "Medium",
    pattern: "1D Dynamic Programming",
    link: "https://leetcode.com/problems/coin-change/",
    gfg: "https://www.geeksforgeeks.org/find-minimum-number-of-coins-that-make-a-change/",
  },
  {
    id: 122,
    title: "Maximum Product Subarray",
    difficulty: "Medium",
    pattern: "1D Dynamic Programming",
    link: "https://leetcode.com/problems/maximum-product-subarray/",
    gfg: "https://www.geeksforgeeks.org/maximum-product-subarray/",
  },
  {
    id: 123,
    title: "Word Break",
    difficulty: "Medium",
    pattern: "1D Dynamic Programming",
    link: "https://leetcode.com/problems/word-break/",
    gfg: "https://www.geeksforgeeks.org/word-break-problem-dp-32/",
  },
  {
    id: 124,
    title: "Longest Increasing Subsequence",
    difficulty: "Medium",
    pattern: "1D Dynamic Programming",
    link: "https://leetcode.com/problems/longest-increasing-subsequence/",
    gfg: "https://www.geeksforgeeks.org/longest-increasing-subsequence-dp-3/",
  },
  {
    id: 125,
    title: "Partition Equal Subset Sum",
    difficulty: "Medium",
    pattern: "1D Dynamic Programming",
    link: "https://leetcode.com/problems/partition-equal-subset-sum/",
    gfg: "https://www.geeksforgeeks.org/partition-problem-dp-18/",
  },
  {
    id: 126,
    title: "Jump Game",
    difficulty: "Medium",
    pattern: "1D Dynamic Programming",
    link: "https://leetcode.com/problems/jump-game/",
    gfg: "https://www.geeksforgeeks.org/minimum-number-of-jumps-to-reach-end-of-a-given-array/",
  },
  {
    id: 127,
    title: "Min Cost Climbing Stairs",
    difficulty: "Easy",
    pattern: "1D Dynamic Programming",
    link: "https://leetcode.com/problems/min-cost-climbing-stairs/",
  },

  // ===== 2D Dynamic Programming =====
  {
    id: 128,
    title: "Unique Paths",
    difficulty: "Medium",
    pattern: "2D Dynamic Programming",
    link: "https://leetcode.com/problems/unique-paths/",
    gfg: "https://www.geeksforgeeks.org/count-possible-paths-top-left-bottom-right-nxm-matrix/",
  },
  {
    id: 129,
    title: "Longest Common Subsequence",
    difficulty: "Medium",
    pattern: "2D Dynamic Programming",
    link: "https://leetcode.com/problems/longest-common-subsequence/",
    gfg: "https://www.geeksforgeeks.org/longest-common-subsequence-dp-4/",
  },
  {
    id: 130,
    title: "Best Time to Buy and Sell Stock with Cooldown",
    difficulty: "Medium",
    pattern: "2D Dynamic Programming",
    link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/",
  },
  {
    id: 131,
    title: "Coin Change 2",
    difficulty: "Medium",
    pattern: "2D Dynamic Programming",
    link: "https://leetcode.com/problems/coin-change-ii/",
    gfg: "https://www.geeksforgeeks.org/coin-change-dp-7/",
  },
  {
    id: 132,
    title: "Target Sum",
    difficulty: "Medium",
    pattern: "2D Dynamic Programming",
    link: "https://leetcode.com/problems/target-sum/",
  },
  {
    id: 133,
    title: "Interleaving String",
    difficulty: "Medium",
    pattern: "2D Dynamic Programming",
    link: "https://leetcode.com/problems/interleaving-string/",
    gfg: "https://www.geeksforgeeks.org/find-if-a-string-is-interleaved-of-two-other-strings-dp-33/",
  },
  {
    id: 134,
    title: "Edit Distance",
    difficulty: "Medium",
    pattern: "2D Dynamic Programming",
    link: "https://leetcode.com/problems/edit-distance/",
    gfg: "https://www.geeksforgeeks.org/edit-distance-dp-5/",
  },
  {
    id: 135,
    title: "Maximal Square",
    difficulty: "Medium",
    pattern: "2D Dynamic Programming",
    link: "https://leetcode.com/problems/maximal-square/",
    gfg: "https://www.geeksforgeeks.org/maximum-size-sub-matrix-with-all-1s-in-a-binary-matrix/",
  },
  {
    id: 136,
    title: "Distinct Subsequences",
    difficulty: "Hard",
    pattern: "2D Dynamic Programming",
    link: "https://leetcode.com/problems/distinct-subsequences/",
    gfg: "https://www.geeksforgeeks.org/count-distinct-subsequences/",
  },
  {
    id: 137,
    title: "Regular Expression Matching",
    difficulty: "Hard",
    pattern: "2D Dynamic Programming",
    link: "https://leetcode.com/problems/regular-expression-matching/",
  },
  {
    id: 138,
    title: "0/1 Knapsack",
    difficulty: "Medium",
    pattern: "2D Dynamic Programming",
    link: "https://leetcode.com/problems/ones-and-zeroes/",
    gfg: "https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/",
  },

  // ===== Greedy =====
  {
    id: 139,
    title: "Maximum Subarray",
    difficulty: "Medium",
    pattern: "Greedy",
    link: "https://leetcode.com/problems/maximum-subarray/",
    gfg: "https://www.geeksforgeeks.org/largest-sum-contiguous-subarray/",
  },
  {
    id: 140,
    title: "Jump Game II",
    difficulty: "Medium",
    pattern: "Greedy",
    link: "https://leetcode.com/problems/jump-game-ii/",
    gfg: "https://www.geeksforgeeks.org/minimum-number-of-jumps-to-reach-end-of-a-given-array/",
  },
  {
    id: 141,
    title: "Gas Station",
    difficulty: "Medium",
    pattern: "Greedy",
    link: "https://leetcode.com/problems/gas-station/",
    gfg: "https://www.geeksforgeeks.org/find-a-tour-that-visits-all-stations/",
  },
  {
    id: 142,
    title: "Hand of Straights",
    difficulty: "Medium",
    pattern: "Greedy",
    link: "https://leetcode.com/problems/hand-of-straights/",
  },
  {
    id: 143,
    title: "Partition Labels",
    difficulty: "Medium",
    pattern: "Greedy",
    link: "https://leetcode.com/problems/partition-labels/",
  },
  {
    id: 144,
    title: "Valid Parenthesis String",
    difficulty: "Medium",
    pattern: "Greedy",
    link: "https://leetcode.com/problems/valid-parenthesis-string/",
  },
  {
    id: 145,
    title: "Non-overlapping Intervals",
    difficulty: "Medium",
    pattern: "Greedy",
    link: "https://leetcode.com/problems/non-overlapping-intervals/",
    gfg: "https://www.geeksforgeeks.org/minimum-number-of-intervals-to-cover-the-target-interval/",
  },
  {
    id: 146,
    title: "Minimum Number of Arrows to Burst Balloons",
    difficulty: "Medium",
    pattern: "Greedy",
    link: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/",
  },

  // ===== Intervals =====
  {
    id: 147,
    title: "Merge Intervals",
    difficulty: "Medium",
    pattern: "Intervals",
    link: "https://leetcode.com/problems/merge-intervals/",
    gfg: "https://www.geeksforgeeks.org/merging-intervals/",
  },
  {
    id: 148,
    title: "Insert Interval",
    difficulty: "Medium",
    pattern: "Intervals",
    link: "https://leetcode.com/problems/insert-interval/",
    gfg: "https://www.geeksforgeeks.org/insert-in-sorted-and-non-overlapping-interval-array/",
  },
  {
    id: 149,
    title: "Meeting Rooms",
    difficulty: "Easy",
    pattern: "Intervals",
    link: "https://leetcode.com/problems/meeting-rooms/",
    gfg: "https://www.geeksforgeeks.org/activity-selection-problem-greedy-algo-1/",
  },
  {
    id: 150,
    title: "Meeting Rooms II",
    difficulty: "Medium",
    pattern: "Intervals",
    link: "https://leetcode.com/problems/meeting-rooms-ii/",
    gfg: "https://www.geeksforgeeks.org/minimum-number-platforms-required-railwaybus-station/",
  },
  {
    id: 151,
    title: "Interval List Intersections",
    difficulty: "Medium",
    pattern: "Intervals",
    link: "https://leetcode.com/problems/interval-list-intersections/",
  },
  {
    id: 152,
    title: "Employee Free Time",
    difficulty: "Hard",
    pattern: "Intervals",
    link: "https://leetcode.com/problems/employee-free-time/",
  },

  // ===== Bit Manipulation =====
  {
    id: 153,
    title: "Single Number",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    link: "https://leetcode.com/problems/single-number/",
    gfg: "https://www.geeksforgeeks.org/find-element-appears-array-every-element-appears-twice/",
  },
  {
    id: 154,
    title: "Number of 1 Bits",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    link: "https://leetcode.com/problems/number-of-1-bits/",
    gfg: "https://www.geeksforgeeks.org/count-set-bits-in-an-integer/",
  },
  {
    id: 155,
    title: "Counting Bits",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    link: "https://leetcode.com/problems/counting-bits/",
  },
  {
    id: 156,
    title: "Reverse Bits",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    link: "https://leetcode.com/problems/reverse-bits/",
    gfg: "https://www.geeksforgeeks.org/write-an-efficient-c-program-to-reverse-bits-of-a-number/",
  },
  {
    id: 157,
    title: "Missing Number",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    link: "https://leetcode.com/problems/missing-number/",
    gfg: "https://www.geeksforgeeks.org/find-the-missing-number/",
  },
  {
    id: 158,
    title: "Sum of Two Integers",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    link: "https://leetcode.com/problems/sum-of-two-integers/",
    gfg: "https://www.geeksforgeeks.org/add-two-numbers-without-using-arithmetic-operators/",
  },
  {
    id: 159,
    title: "Bitwise AND of Numbers Range",
    difficulty: "Medium",
    pattern: "Bit Manipulation",
    link: "https://leetcode.com/problems/bitwise-and-of-numbers-range/",
  },
  {
    id: 160,
    title: "Power of Two",
    difficulty: "Easy",
    pattern: "Bit Manipulation",
    link: "https://leetcode.com/problems/power-of-two/",
    gfg: "https://www.geeksforgeeks.org/program-to-find-whether-a-no-is-power-of-two/",
  },

  // ===== Math & Geometry =====
  {
    id: 161,
    title: "Rotate Image",
    difficulty: "Medium",
    pattern: "Math & Geometry",
    link: "https://leetcode.com/problems/rotate-image/",
    gfg: "https://www.geeksforgeeks.org/inplace-rotate-square-matrix-by-90-degrees/",
  },
  {
    id: 162,
    title: "Spiral Matrix",
    difficulty: "Medium",
    pattern: "Math & Geometry",
    link: "https://leetcode.com/problems/spiral-matrix/",
    gfg: "https://www.geeksforgeeks.org/print-a-given-matrix-in-spiral-form/",
  },
  {
    id: 163,
    title: "Set Matrix Zeroes",
    difficulty: "Medium",
    pattern: "Math & Geometry",
    link: "https://leetcode.com/problems/set-matrix-zeroes/",
    gfg: "https://www.geeksforgeeks.org/a-boolean-matrix-question/",
  },
  {
    id: 164,
    title: "Happy Number",
    difficulty: "Easy",
    pattern: "Math & Geometry",
    link: "https://leetcode.com/problems/happy-number/",
  },
  {
    id: 165,
    title: "Plus One",
    difficulty: "Easy",
    pattern: "Math & Geometry",
    link: "https://leetcode.com/problems/plus-one/",
  },
  {
    id: 166,
    title: "Pow(x, n)",
    difficulty: "Medium",
    pattern: "Math & Geometry",
    link: "https://leetcode.com/problems/powx-n/",
    gfg: "https://www.geeksforgeeks.org/write-a-c-program-to-calculate-powxn/",
  },
  {
    id: 167,
    title: "Multiply Strings",
    difficulty: "Medium",
    pattern: "Math & Geometry",
    link: "https://leetcode.com/problems/multiply-strings/",
    gfg: "https://www.geeksforgeeks.org/multiply-large-numbers-represented-as-strings/",
  },
  {
    id: 168,
    title: "Detect Squares",
    difficulty: "Medium",
    pattern: "Math & Geometry",
    link: "https://leetcode.com/problems/detect-squares/",
  },

  // ===== Union Find =====
  {
    id: 169,
    title: "Number of Connected Components in Undirected Graph",
    difficulty: "Medium",
    pattern: "Union Find",
    link: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/",
    gfg: "https://www.geeksforgeeks.org/connected-components-in-an-undirected-graph/",
  },
  {
    id: 170,
    title: "Redundant Connection",
    difficulty: "Medium",
    pattern: "Union Find",
    link: "https://leetcode.com/problems/redundant-connection/",
  },
  {
    id: 171,
    title: "Accounts Merge",
    difficulty: "Medium",
    pattern: "Union Find",
    link: "https://leetcode.com/problems/accounts-merge/",
  },
  {
    id: 172,
    title: "Longest Consecutive Sequence (UF)",
    difficulty: "Medium",
    pattern: "Union Find",
    link: "https://leetcode.com/problems/longest-consecutive-sequence/",
  },
  {
    id: 173,
    title: "Number of Provinces",
    difficulty: "Medium",
    pattern: "Union Find",
    link: "https://leetcode.com/problems/number-of-provinces/",
    gfg: "https://www.geeksforgeeks.org/find-number-of-islands/",
  },
  {
    id: 174,
    title: "Swim in Rising Water",
    difficulty: "Hard",
    pattern: "Union Find",
    link: "https://leetcode.com/problems/swim-in-rising-water/",
  },

  // ===== Advanced Graph =====
  {
    id: 175,
    title: "Network Delay Time",
    difficulty: "Medium",
    pattern: "Advanced Graph",
    link: "https://leetcode.com/problems/network-delay-time/",
    gfg: "https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/",
  },
  {
    id: 176,
    title: "Cheapest Flights Within K Stops",
    difficulty: "Medium",
    pattern: "Advanced Graph",
    link: "https://leetcode.com/problems/cheapest-flights-within-k-stops/",
  },
  {
    id: 177,
    title: "Reconstruct Itinerary",
    difficulty: "Hard",
    pattern: "Advanced Graph",
    link: "https://leetcode.com/problems/reconstruct-itinerary/",
  },
  {
    id: 178,
    title: "Min Cost to Connect All Points",
    difficulty: "Medium",
    pattern: "Advanced Graph",
    link: "https://leetcode.com/problems/min-cost-to-connect-all-points/",
    gfg: "https://www.geeksforgeeks.org/prims-minimum-spanning-tree-mst-greedy-algo-5/",
  },
  {
    id: 179,
    title: "Shortest Path in Grid with Obstacles",
    difficulty: "Hard",
    pattern: "Advanced Graph",
    link: "https://leetcode.com/problems/shortest-path-in-a-grid-with-obstacles-elimination/",
  },

  // ===== String =====
  {
    id: 180,
    title: "Longest Common Prefix",
    difficulty: "Easy",
    pattern: "String",
    link: "https://leetcode.com/problems/longest-common-prefix/",
    gfg: "https://www.geeksforgeeks.org/longest-common-prefix-using-sorting/",
  },
  {
    id: 181,
    title: "Valid Palindrome II",
    difficulty: "Easy",
    pattern: "String",
    link: "https://leetcode.com/problems/valid-palindrome-ii/",
  },
  {
    id: 182,
    title: "Longest Palindromic Subsequence",
    difficulty: "Medium",
    pattern: "String",
    link: "https://leetcode.com/problems/longest-palindromic-subsequence/",
    gfg: "https://www.geeksforgeeks.org/longest-palindromic-subsequence-dp-12/",
  },
  {
    id: 183,
    title: "String to Integer (atoi)",
    difficulty: "Medium",
    pattern: "String",
    link: "https://leetcode.com/problems/string-to-integer-atoi/",
    gfg: "https://www.geeksforgeeks.org/write-your-own-atoi/",
  },
  {
    id: 184,
    title: "Minimum Remove to Make Valid Parentheses",
    difficulty: "Medium",
    pattern: "String",
    link: "https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/",
  },
  {
    id: 185,
    title: "Longest Substring with At Most K Distinct Characters",
    difficulty: "Medium",
    pattern: "String",
    link: "https://leetcode.com/problems/longest-substring-with-at-most-k-distinct-characters/",
  },

  // ===== Matrix / Grid =====
  {
    id: 186,
    title: "Valid Sudoku",
    difficulty: "Medium",
    pattern: "Matrix",
    link: "https://leetcode.com/problems/valid-sudoku/",
    gfg: "https://www.geeksforgeeks.org/check-if-given-sudoku-board-configuration-is-valid-or-not/",
  },
  {
    id: 187,
    title: "Game of Life",
    difficulty: "Medium",
    pattern: "Matrix",
    link: "https://leetcode.com/problems/game-of-life/",
    gfg: "https://www.geeksforgeeks.org/program-for-conways-game-of-life/",
  },
  {
    id: 188,
    title: "Word Search",
    difficulty: "Medium",
    pattern: "Matrix",
    link: "https://leetcode.com/problems/word-search/",
    gfg: "https://www.geeksforgeeks.org/search-a-word-in-a-2d-grid-of-characters/",
  },
  {
    id: 189,
    title: "Maximal Rectangle",
    difficulty: "Hard",
    pattern: "Matrix",
    link: "https://leetcode.com/problems/maximal-rectangle/",
    gfg: "https://www.geeksforgeeks.org/maximum-size-rectangle-binary-sub-matrix-1s/",
  },

  // ===== Design =====
  {
    id: 190,
    title: "LRU Cache",
    difficulty: "Medium",
    pattern: "Design",
    link: "https://leetcode.com/problems/lru-cache/",
    gfg: "https://www.geeksforgeeks.org/lru-cache-implementation/",
  },
  {
    id: 191,
    title: "LFU Cache",
    difficulty: "Hard",
    pattern: "Design",
    link: "https://leetcode.com/problems/lfu-cache/",
  },
  {
    id: 192,
    title: "Design Twitter",
    difficulty: "Medium",
    pattern: "Design",
    link: "https://leetcode.com/problems/design-twitter/",
  },
  {
    id: 193,
    title: "Implement Queue using Stacks",
    difficulty: "Easy",
    pattern: "Design",
    link: "https://leetcode.com/problems/implement-queue-using-stacks/",
    gfg: "https://www.geeksforgeeks.org/queue-using-stacks/",
  },
  {
    id: 194,
    title: "Implement Stack using Queues",
    difficulty: "Easy",
    pattern: "Design",
    link: "https://leetcode.com/problems/implement-stack-using-queues/",
    gfg: "https://www.geeksforgeeks.org/implement-stack-using-queue/",
  },
  {
    id: 195,
    title: "Design HashMap",
    difficulty: "Easy",
    pattern: "Design",
    link: "https://leetcode.com/problems/design-hashmap/",
    gfg: "https://www.geeksforgeeks.org/implementing-our-own-hash-table-with-separate-chaining-in-java/",
  },

  // ===== Miscellaneous =====
  {
    id: 196,
    title: "Find the Duplicate Number",
    difficulty: "Medium",
    pattern: "Miscellaneous",
    link: "https://leetcode.com/problems/find-the-duplicate-number/",
    gfg: "https://www.geeksforgeeks.org/find-the-duplicate-number/",
  },
  {
    id: 197,
    title: "Majority Element",
    difficulty: "Easy",
    pattern: "Miscellaneous",
    link: "https://leetcode.com/problems/majority-element/",
    gfg: "https://www.geeksforgeeks.org/majority-element/",
  },
  {
    id: 198,
    title: "Next Permutation",
    difficulty: "Medium",
    pattern: "Miscellaneous",
    link: "https://leetcode.com/problems/next-permutation/",
    gfg: "https://www.geeksforgeeks.org/next-permutation/",
  },
  {
    id: 199,
    title: "Largest Number",
    difficulty: "Medium",
    pattern: "Miscellaneous",
    link: "https://leetcode.com/problems/largest-number/",
    gfg: "https://www.geeksforgeeks.org/given-an-array-of-numbers-arrange-the-numbers-to-form-the-biggest-number/",
  },
  {
    id: 200,
    title: "Basic Calculator II",
    difficulty: "Medium",
    pattern: "Miscellaneous",
    link: "https://leetcode.com/problems/basic-calculator-ii/",
    gfg: "https://www.geeksforgeeks.org/expression-evaluation/",
  },
];
